# Generated by Django 5.0.7 on 2024-07-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id_interested', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('applicant', models.CharField(max_length=100)),
            ],
        ),
    ]
